### ISSUE TITLE
Animation buguée

### ISSUE THREAD

**Issue by Mistergix** [are00dynamic-2018/Souverains-des-flocons#4]
Le modèle marche, maintenant c'est la fenêtre tkinter qui bug un peu.

Quand on clique trop rapidement sur Next Step, ou que auto dure trop longtemps la fenêtre alterne entre "Not responding" et normal

**Comment by Juju49** [comment]
Semble fonctionner mieux dans opti2 car le draw est devenu parallèle et continu.
