### ISSUE TITLE
Dessins inutiles

### ISSUE THREAD

**Issue by Mistergix** [are00dynamic-2018/Souverains-des-flocons#5]
On remarque que a chaque étape, de nombreuses cellules (celles éloignées du centre) restent identiques à elles mêmes. Or actuellement, dans view.py, a chaque iteration, on refait le tour entier des cellules pour les redessiner, il faudrait optimiser cela. Par exemple rajouter un champs dans HexaCell que l'on met a jour en meme temps que l'état. Ce champs indique si une cellule doit être redessinée : 

+ Si son état précedent est différent de l'état nouveau et que l'état nouveau est inférieur ou égal à 1 (s'il est plus grand, on **met quand même à jour l'état** mais on ne doit pas redessiner la cellule car tout état plus grand que 1 implique que la couleur soit blanche.

**Comment by Juju49** [comment]
# Problème réglé dans la branche opti2
il suffira de merge les branches et on devrais y arriver. ça fonctionne chez moi
